# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# ----------------
# Builder stage
# ----------------
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /app

# Install dependencies (ignore scripts to avoid prepublish hooks)
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# ----------------
# Runner stage
# ----------------
FROM node:lts-alpine AS runner
WORKDIR /app

# Only copy build artifacts and package files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install only production dependencies
RUN npm ci --only=production --ignore-scripts

# Default command to start the MCP server over stdio
CMD ["node", "dist/index.js"]
